---
- name: Examples of juniper_junos_ping
  hosts: all
  connection: local
  gather_facts: no
  roles:
    - juniper.junos

  tasks:
    - name: Ping Test. Fails if any packets lost.
      juniper_junos_ping:
        dest: "1.1.1.2"
        source: "1.1.1.1"
      register: response

    - name: Print the response.
      debug:
        var: response
